/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-12-02 21:26:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BookstorePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/Student/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QEModule_SeleniumCucumber_PracticeSBA_Template/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1573024162020L));
    _jspx_dependants.put("/WEB-INF/views/Header.jsp", Long.valueOf(1554847728000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Bookstore Page</title>\n");
      out.write("<style>\n");
      out.write("\t#book_list {\n");
      out.write("\t\tmargin: 10px;\n");
      out.write("\t\tborder: 5px solid #333333;\n");
      out.write("\t\tbackground-color: #cccccc;\n");
      out.write("\t\twidth: 90%;\n");
      out.write("\t\theight: auto;\n");
      out.write("\t}\n");
      out.write("\t.book_item {\n");
      out.write("\t\tvertical-align: top;\n");
      out.write("\t\tdisplay: inline-block;\n");
      out.write("\t\tmargin: 10px;\n");
      out.write("\t\tborder: 3px solid black;\n");
      out.write("\t\tbackground-color: #aaaaaa;\n");
      out.write("\t\twidth: 150px;\n");
      out.write("\t\theight: 200px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tinput[value=\"Add Item\"]:hover  {\n");
      out.write("\t\tbackground-color: black;\n");
      out.write("\t\tcolor: white;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.book_title {\n");
      out.write("\t\twidth: 95%;\n");
      out.write("\t\theight: 50%;\n");
      out.write("\t\tmargin: auto;\n");
      out.write("\t\tborder: 2px solid black;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.book_title > p {\n");
      out.write("\t\tmargin-left: 10px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<h1>Bookstore</h1>\n");
      out.write("\t");
      out.write("<head>\n");
      out.write("\t<style>\n");
      out.write("\t\t/* Dropdown Button */\n");
      out.write("\t\t.dropbtn {\n");
      out.write("\t\t  background-color: #4CAF50;\n");
      out.write("\t\t  color: white;\n");
      out.write("\t\t  padding: 16px;\n");
      out.write("\t\t  font-size: 16px;\n");
      out.write("\t\t  border: none;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t/* The container <div> - needed to position the dropdown content */\n");
      out.write("\t\t.dropdown {\n");
      out.write("\t\t  position: relative;\n");
      out.write("\t\t  display: inline-block;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t/* Dropdown Content (Hidden by Default) */\n");
      out.write("\t\t.dropdown-content {\n");
      out.write("\t\t  display: none;\n");
      out.write("\t\t  position: absolute;\n");
      out.write("\t\t  background-color: #f1f1f1;\n");
      out.write("\t\t  min-width: 160px;\n");
      out.write("\t\t  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\n");
      out.write("\t\t  z-index: 1;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t/* Links inside the dropdown */\n");
      out.write("\t\t.dropdown-content a {\n");
      out.write("\t\t  color: black;\n");
      out.write("\t\t  padding: 12px 16px;\n");
      out.write("\t\t  text-decoration: none;\n");
      out.write("\t\t  display: block;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t/* Change color of dropdown links on hover */\n");
      out.write("\t\t.dropdown-content a:hover {background-color: #ddd;}\n");
      out.write("\t\t\n");
      out.write("\t\t/* Show the dropdown menu on hover */\n");
      out.write("\t\t.dropdown:hover .dropdown-content {display: block;}\n");
      out.write("\t\t\n");
      out.write("\t\t/* Change the background color of the dropdown button when the dropdown content is shown */\n");
      out.write("\t\t.dropdown:hover .dropbtn {background-color: #3e8e41;}\n");
      out.write("\t</style>\n");
      out.write("</head>\n");
      out.write("<header>\n");
      out.write("\t<div class=\"dropdown\">\n");
      out.write("\t\t<button class=\"dropbtn\">Menu</button>\n");
      out.write("\t\t<div class=\"dropdown-content\">\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Signup Page</a>\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/successPage\">Success Page</a>\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bookstore\">Bookstore Page</a>\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/iFramesPage\">iFrames Page</a>\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/showAlertPage\">Alert Page</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</header>");
      out.write("\n");
      out.write("\t<div id=\"book_list\">\n");
      out.write("\t\t<form id=\"book1\" class=\"book_item\" action=\"addToCart\" method=\"POST\">\n");
      out.write("\t\t\t<div class=\"book_title\">\n");
      out.write("\t\t\t\t<p>SQL for Java Developers</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"book_purchase\">\n");
      out.write("\t\t\t\t<div class=\"book_price\">\n");
      out.write("\t\t\t\t\t<p>$12.99</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"add_button\">\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"price\" value=\"12.99\" />\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"title\" value=\"SQL for Java Developers\" />\n");
      out.write("\t\t\t\t\t<input id=\"book1Add\" type=\"submit\" value=\"Add Item\"/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t\n");
      out.write("\t\t<form id=\"book2\" class=\"book_item\" action=\"addToCart\" method=\"POST\">\n");
      out.write("\t\t\t<div class=\"book_title\">\n");
      out.write("\t\t\t\t<p>Java Projects</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"book_purchase\">\n");
      out.write("\t\t\t\t<div class=\"book_price\">\n");
      out.write("\t\t\t\t\t<p>$14.99</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"add_button\">\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"price\" value=\"14.99\" />\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"title\" value=\"Java Projects\" />\n");
      out.write("\t\t\t\t\t<input id=\"book2Add\" type=\"submit\" value=\"Add Item\"/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<form id=\"book3\" class=\"book_item\" action=\"addToCart\" method=\"POST\">\n");
      out.write("\t\t\t<div class=\"book_title\">\n");
      out.write("\t\t\t\t<p>Testing Spring MVC Projects</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"book_purchase\">\n");
      out.write("\t\t\t\t<div class=\"book_price\">\n");
      out.write("\t\t\t\t\t<p>$21.99</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"add_button\">\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"price\" value=\"21.99\" />\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"title\" value=\"Testing Spring MVC Projects\" />\n");
      out.write("\t\t\t\t\t<input id=\"book3Add\" type=\"submit\" value=\"Add Item\"/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<p>Shopping Cart</p>\n");
      out.write("\t\t\t<table>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th>Title</th>\n");
      out.write("\t\t\t\t\t<th>Price</th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<p id=\"cart_total\">Cart Total: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartTotal}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<form action=\"placeOrder\" method=\"POST\">\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Place Order\" />\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<form action=\"clearShoppingCart\" method=\"POST\">\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Clear Cart\"/>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/BookstorePage.jsp(103,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/BookstorePage.jsp(103,4) '${bookCart}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${bookCart}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/BookstorePage.jsp(103,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("book");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t<tr>\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\t\t\t\t\t</tr>\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
